### ISSUE TITLE
License for content?

### ISSUE THREAD

**Issue by sofiahall** [typoes/harry-potter-gen-z#54]
Hello I'm interested in contributing to the project, but would like to know what the text is / will be licensed under. I didn't see a license file.

Thanks

**Comment by CatFishing4Guyz** [comment]
If I were to add a license, it would probably be MIT. Maybe I should add one rn?

**Comment by typoes** [comment]
Thank you @CatFishing4Guyz for adding the license! Merged: https://github.com/typoes/harry-potter-gen-z/pull/60
