### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by DovePod** [typoes/harry-potter-gen-z#87]
Hey, so I have noticed that you have been offline for some time now. To make sure this meme won't die, can you make me a maintainer, so that I can approve pulls? I feel like I can be helpful to you in this way!

**Comment by DaCuteRaccoon** [comment]
@DovePod yeah good idea, but I think we shouldn't get a maintainer...

But a group of maintainers!

**Comment by DaCuteRaccoon** [comment]
I propose that you should make an organization and maybe give people you trust permissions to maintain and accept pull requests. I would be up for this. I am a moderator on some other sites. @DovePod would also probably be too. That would make this meme not die ^^^ and keep it going faster and better. If we really want to do this more, I could put this in the middle of one of my youtube videos (lol I don't know how that would go) and get popularity. You should at least consider this.

**Comment by typoes** [comment]
Yes, we can do this! I'll start getting it set up, but it's a pain to do from my phone. Feel free to ping me again if it takes me too long!

**Comment by typoes** [comment]
Switching it to an organization seemed more involved than just adding people directly. I can change this in the future, if needed, but I'll stick with this for now. 

@DaCuteRaccoon @DovePod -- added you both :) Thanks for offering to help!
